#database connection config
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql:///411
    username: root
    password: 123123
  mvc: #映射路径
    view:
      prefix: /
      suffix: .jsp

mybatis:
  type-aliases-package: com.example.demo.pojo
  mapper-locations: classpath:/mapper/*Mapper.xml
